authorName: NNI Example
experimentName: NN IE Tuning
trialConcurrency: 4
maxExecDuration: 2h
maxTrialNum: 120
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: minimize
trial:
  command: python NN.py
  codeDir: .
